// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmxuxkinmltglvldwido.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteHV4a2lubWx0Z2x2bGR3aWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTkyNTAsImV4cCI6MjA2NDU3NTI1MH0.2xsTcQPiQWOr3CRcv3c4GWIYc35dQ1OA6YtcrfpLb74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);